config/routes.rb
Photodiary::Application.routes.draw do

  root to: 'home#index'
  
  resources :users do
    resources :albums
  end
  
  resources :albums do
    resources :photos do
      resources :comments
    end
  end
  
  match '/login', to: 'users#login', via: :get
  match '/login', to: 'users#login_process', via: :post
  match '/logout', to: 'users#logout'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo

  validates_presence_of :body

  attr_protected :user_id, :photo_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login, only: [:create, :edit, :update]

  # POST /albums/:album_id/photo/:photo_id/comments
  def create
    @photo = Photo.find params[:photo_id]
    @comment = @photo.comments.build params[:comment]
    @comment.user = current_user

    if @comment.save
      flash[:message] = t('comments.new.created')
      redirect_to controller: 'photos', action: 'show', album_id: @photo.album_id, id: @photo.id
    else
      render :new
    end
  end

  # GET /albums/:album_id/photos/:photo_id/comments/:id/edit
  def edit
    load_comment_and_photo
    redirect_to root_path and return unless is_owner? @comment.user_id
  end

  # PUT /albums/:album_id/photos/:photo_id/comments/:id
  def update
    load_comment_and_photo
    redirect_to root_path and return unless is_owner? @comment.user_id

    if @comment.update_attributes params[:comment]
      flash[:message] = t('comments.edit.updated')
      redirect_to controller: 'photos', action: 'show', album_id: @photo.album_id, id: @photo.id and return
    else
      render :edit and return
    end
  end

  private

  def load_comment_and_photo
    @comment = Comment.find params[:id]
    @photo = @comment.photo
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def has_comment_rights?(comment)
    current_user && comment.user_id == current_user.id
  end 
end

app/views/comments/_form.html.erb
<% if logged_in? %>
  <% if @comment.errors.any? %>
    <div class="error_explanation">
      <h2><%= t('error_occur', count: @comment.errors.count) %>:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for([@photo.album, @photo, @comment]) do |f| %>
    <div class="field">
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit t('helpers.submit.publish') %>
    </div>
  <% end %>
<% end %>

app/views/comments/_index.html.erb
<div class="commentsHolder" id="comments">
  <h2><%= t('.comments') %></h2>
  <% if @photo.comments.count > 0 %>
    <% @photo.comments.each do |c| %>
      <div class="objHolder" id="comment-<%= c.id %>">
        <%= link_to image_tag(UserDecorator.decorate(c.user).avatar_src, border: 0), user_albums_path(c.user), title: t('albums.index.albums_of', user: @user.username) %>
        <div class="comment">
          <p><%= c.body %></p>
          <% if has_comment_rights?(c) %>
            <%= link_to t('edit'), edit_album_photo_comment_path(@album, @photo, c), class: :commentEdit %> |
          <% end %>
          <span class="commentDate">
            <% link_text = t('.published_on', date: c.created_at.strftime('%d.%m.%Y %H:%M')) %>
            <% if c.updated_at > c.created_at %>
              <% link_text += ', '+t('.last_edit', date: c.updated_at.strftime('%d.%m.%Y %H:%M')) %>
            <% end %>
            <%= link_to link_text, album_photo_path(@album, @photo)+'#comment-'+c.id.to_s %>
          </span>
        </div>
        <div class="clear"></div>
      </div>
    <% end %>
  <% else %>
    <p><%= t('.no_comments') %></p>
  <% end %>
  <div class="clear"></div>
</div>

app/views/comments/edit.html.erb
<% page_title = t('.edit_comment') %>
<% content_for :page_title, page_title %>

<div class="title">
  <h1><%= page_title %></h1>
  <div class="links">
    <%= link_to t('.back_to_photo'), album_photo_path(@photo.album, @photo) %> |
  </div>
</div>

<%= render 'form' %>

app/views/comments/new.html.erb
<% page_title = t('.new_comment') %>
<% content_for :page_title, page_title %>

<div class="title">
  <h1><%= page_title %></h1>
</div>

<%= render 'form' %>