config/routes.rb
Photodiary::Application.routes.draw do

  root to: 'home#index'
  
  resources :users do
    resources :albums
  end
  
  resources :albums do
    resources :photos do
      resources :comments
    end
  end
  
  match '/login', to: 'users#login', via: :get
  match '/login', to: 'users#login_process', via: :post
  match '/logout', to: 'users#logout'

  

end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base  
  has_many :albums, dependent: :destroy
  has_many :photos, through: :albums
  has_many :comments, dependent: :destroy

  attr_accessor :password, :remove_photo

  attr_protected :hashed_password, :salt

  mount_uploader :photo, AvatarUploader

  before_save :create_hashed_password, :update_photo

  validates_presence_of :username
  validates_uniqueness_of :username, if: -> { username.present? }
  validates_presence_of :password, on: :create
  validates_length_of :password, minimum: 6, if: -> { password.present? }
  validates_confirmation_of :password, if: -> { password.present? }
  validates_presence_of :email
  validates_uniqueness_of :email, if: -> { email.present? }
  validates_format_of :email, with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, if: -> { email.present? }

  def self.authenticate(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    return user if user.has_password?(password)
    nil
  end

  def has_password?(password)
    self.hashed_password == User.encrypt(password, salt)
  end

  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest(password+salt)
  end

  def generate_salt
    self.object_id.to_s + rand.to_s
  end

  def avatar_standard
    photo.thumb.try(:url)
  end

  def has_photo?
    photo.url ? true : false
  end

  def avatar_small
    photo.small_thumb.try(:url)
  end

  def albums_count
    albums.size
  end

  def photos_count
    photos.size
  end

  private

  def create_hashed_password
    if password.present?
      new_salt = generate_salt
      write_attribute(:salt, new_salt)
      write_attribute(:hashed_password, User.encrypt(password, new_salt))
    end
  end

  def update_photo
    write_attribute(:photo, '') if remove_photo.present? && remove_photo == '1'
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  before_filter :require_login, only: [:edit, :update, :destroy, :logout]

  # GET /users
  def index
    @users = UserDecorator.decorate(User.all)
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    redirect_to root_path and return unless is_owner? @user.id
  end

  # POST /users
  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:message] = t('users.new.created')
      redirect_to @user and return
    else
       render :new and return
    end
  end

  # PUT /users/1
  def update
    @user = User.find(params[:id])
    redirect_to root_path and return unless is_owner? @user.id

    if params[:user][:photo]
      params[:user][:remove_photo] = nil
    end

    if @user.update_attributes(params[:user])
      flash[:message] = t('users.edit.updated')
      redirect_to @user and return
    else
      render :edit and return
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    redirect_to root_path and return unless is_owner? @user.id

    @user.destroy

    redirect_to users_path and return
  end

  # GET /login
  def login
    @user = User.new
  end

  # POST /login
  def login_process
    session[:current_user] = User.authenticate(params[:user][:username], params[:user][:password])
    if session[:current_user]
      flash[:message] = t('users.login.succeeded')
      redirect_to root_path and return
    else
      flash.now[:error] = t('users.login.error')
      @user = User.new
      render :login and return
    end
  end

  # DELETE /logout
  def logout
    reset_session
    flash[:message] = t('users.logout.succeeded')
    redirect_to root_path and return
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% page_title = t('.edit_user') %>
<% content_for :page_title, page_title %>

<div class="title">
  <h1><%= page_title %></h1>
  <div class="links">
    <%= link_to t('preview'), current_user %> |
    <%= link_to t('delete'), current_user, confirm: t('.delete_msg'), method: :delete %> |
  </div>
</div>
<%= render 'messages' %>

<%= form_for(@user, html: { multipart: true }) do |f| %>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username, disabled: true %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, disabled: true %>
  </div>
  <% if @user.has_photo? %>
    <div class="field">
      <%= image_tag(@user.photo.preview.url) %><br />
      <%= f.check_box :remove_photo %>
      <%= f.label :remove_photo %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<% page_title = t('.users_of_site', site: t('sitename')) %>
<% content_for :page_title, page_title %>

<div class="title">
  <h1><%= t('.users_of_site_are', count: @users.size, site: t('sitename')) %></h1>
</div>
<%= render 'messages' %>

<div class="usersHolder">
  <% @users.each_with_index do |user, i| %>
    <div class="usrHolder bm rm">
      <%= link_to image_tag(user.avatar_src, border: 0), user_path(user), title: user.username, class: "userLink" %>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

app/views/users/login.html.erb
<% page_title = t('login') %>
<% content_for :page_title, page_title %>

<div class="title">
  <h1><%= page_title %></h1>
</div>
<%= render 'messages' %>

<%= form_for(@user, url: login_path) do |f| %>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit t('helpers.submit.login') %>
  </div>
<% end %>

app/views/users/new.html.erb
<% page_title = t('.registration') %>
<% content_for :page_title, page_title %>

<div class="title">
  <h1><%= page_title %></h1>
</div>
<%= render 'messages' %>

<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit t('.registration') %>
  </div>
<% end %>

app/views/users/show.html.erb
<% if has_user_riths? %>
  <% page_title = t('.profile') %>
<% else %>
  <% page_title = t('.preview_user', user: @user.username) %>
<% end %>
<% content_for :page_title, page_title %>

<div class="title">
  <h1><%= page_title %></h1>
  <% if has_user_riths? %>
    <div class="links">
      <%= link_to t('edit'), edit_user_path(current_user) %> |
      <%= link_to t('delete'), user_path(current_user), confirm: t('users.edit.delete_msg'), method: :delete %> |
    </div>
  <% end %>
</div>
<%= render 'messages' %>

<% if @user.has_photo? %>
  <%= image_tag(@user.photo.preview.url) %><br />
<% end %>
<p>
  <b><%= User.human_attribute_name('full_name') %>:</b>
  <%= @user.full_name %>
</p>

<p>
  <b><%= User.human_attribute_name('email') %>:</b>
  <%= @user.email %>
</p>

<p>
  <b><%= User.human_attribute_name('description') %>:</b>
  <%= @user.description %>
</p>

<p>
  <% photos_cnt = @user.photos_count %>
  <% albums_cnt = @user.albums_count %>
  <b><%= link_to t('.total_photo', count: photos_cnt)+' '+t('.in_album', count: albums_cnt), user_albums_path(@user) %></b>
</p>