config/routes.rb
Photodiary::Application.routes.draw do

  root to: 'home#index'
  
  resources :users do
    resources :albums
  end
  
  resources :albums do
    resources :photos do
      resources :comments
    end
  end
  
  match '/login', to: 'users#login', via: :get
  match '/login', to: 'users#login_process', via: :post
  match '/logout', to: 'users#logout'

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base  
  include ExifData

  belongs_to :album
  has_many :comments, dependent: :destroy, order: 'comments.created_at ASC'

  mount_uploader :file, PhotoUploader

  before_create :set_photo_attributes

  validates_presence_of :file, on: :create

  attr_protected :album_id

  def previous_photo
    Photo.where("album_id = ? AND id > ?", album_id, id).order("id ASC").first
  end

  def next_photo
    Photo.where("album_id = ? AND id < ?", album_id, id).order("id DESC").first
  end

  def increment_views
    increment!(:views)
  end

  def self.latest(number)
    order("id DESC").limit(number)
  end

  private

  def set_photo_attributes
    extract_exif_data(file.path)
    write_attribute(:camera_model, get_model)
    write_attribute(:date_taken, get_date_time)
    write_attribute(:exposure_time, get_exposure_time)
    write_attribute(:f_number, get_f_number)
    write_attribute(:iso_speed, get_iso_speed)
    write_attribute(:flength_35mm_film, get_focal_length_in_35mm_film)
    write_attribute(:flash, get_flash)
    lat = get_latitude
    long = get_longitude
    write_attribute(:latitude, lat)
    write_attribute(:longitude, long)
    write_attribute(:gps_address, get_gps_address(lat, long)) if lat && long
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :load_album, :load_album_owner
  before_filter :require_login, only: [:new, :create, :edit, :update, :destroy]

  # GET /albums/:album_id/photos
  def index
    @photos = @album.photos
  end

  # GET /albums/:album_id/photos/:id
  def show
    @photo = PhotoDecorator.find(params[:id])
    @photo.increment_views
  end

  # GET /albums/:album_id/photos/new
  def new
    redirect_to root_path and return unless is_owner? @album.user_id
    @photo = @album.photos.build
  end

  # GET /albums/:album_id/photos/:id/edit
  def edit
    redirect_to root_path and return unless is_owner? @album.user_id
    @photo = @album.photos.find(params[:id])
  end

  # POST /albums/:album_id/photos
  def create
    redirect_to root_path and return unless is_owner? @album.user_id
    @photo = @album.photos.build(params[:photo])

    if @photo.save
      flash[:message] = t('photos.new.created')
      redirect_to [@album, @photo] and return
    else
      render :new and return
    end
  end

  # PUT /albums/:album_id/photos/:id
  def update
    redirect_to root_path and return unless is_owner? @album.user_id
    @photo = @album.photos.find(params[:id])

    if @photo.update_attributes(params[:photo])
      flash[:message] = t('photos.edit.updated')
      redirect_to [@album, @photo] and return
    else
      render :edit and return
    end
  end

  # DELETE /albums/:album_id/photos/1
  def destroy
    redirect_to root_path and return unless is_owner? @album.user_id
    @photo = @album.photos.find(params[:id])    

    @photo.destroy

    redirect_to album_photos_url(@album) and return
  end

  private

  def load_album
    @album = Album.find(params[:album_id])
  end

  def load_album_owner
    @user = UserDecorator.find(@album.user_id)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/edit.html.erb
<% page_title = t('edit') %>
<% content_for :page_title, page_title %>

<div class="title">
  <h1><%= page_title %></h1>
  <div class="links">
    <%= link_to t('.preview_photo'), album_photo_path(@album, @photo) %> |
    <%= link_to t('delete'), album_photo_path(@album, @photo), confirm: t('.delete_msg'), method: :delete %> |
  </div>
</div>
<%= render 'messages' %>

<%= form_for([@album, @photo]) do |f| %>
  <%= image_tag(@photo.file.preview.url) %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :place_taken %><br />
    <%= f.text_field :place_taken %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/index.html.erb
<% page_title = t('.album_belongs_to_user', album: @album.title, user: @user.username) %>
<% content_for :page_title, page_title %>

<div class="title">
  <h1>
    <%= page_title %>
    <%= link_to image_tag(@user.avatar_src(:small), border: 0), user_albums_path(@user), title: t('albums.index.albums_of', user: @user.username) %>
  </h1>
  <div class="links">
    <% if has_album_rights? %> 
      <%= link_to t('albums.edit.add_photo'), new_album_photo_path(@album) %> |
      <%= link_to t('edit'), edit_user_album_path(@user, @album) %> |
      <%= link_to t('delete'), user_album_path(@user, @album), confirm: t('albums.edit.delete_msg'), method: :delete %> |
    <% else %>
      <% photos_cnt = @album.photos_count %>
      (<%= t('.cnt_photos', count: photos_cnt) %>)
  <% end %>
  </div>
</div>

<%= render 'messages' %>

<div class="photoHolder">
  <% if @photos.size > 0 %>
    <% @photos.each_with_index do |photo, i| %>
      <div class="objHolder bm <%= 'rm' if i % 5 != 4 %>">
        <%= link_to image_tag(photo.file.thumb.url, border: 0), album_photo_path(@album, photo), title: photo.title, class: "photoLink" %>
      </div>
    <% end %>
  <% else %>
    <p><%= t('.no_photos') %></p>
  <% end %>
  <div class="clear"></div>
</div>

<% if @album.description %>
  <div class="albumDesc">
    <p><%= @album.description %></p>
    <div class="clear"></div>
  </div>
<% end %>

app/views/photos/new.html.erb
<% page_title = t('.add_photo_to_album', album: @album.title) %>
<% content_for :page_title, page_title %>

<div class="title">
  <h1><%= page_title %></h1>
  <div class="links">
    <%= link_to t('.back_to_album'), album_photos_path(@album) %>
  </div>
</div>
<%= render 'messages' %>

<%= form_for([@album, @photo]) do |f| %>
  <div class="field">
    <%= f.label :file, t('.choose_photo') %>
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit t('.upload') %>
  </div>
<% end %>

app/views/photos/show.html.erb
<% if @photo.title && !@photo.title.empty? %>
  <% page_title = @photo.title+' - '+@album.title %>
<% else %>
  <% page_title = @album.title %>
<% end %>
<% content_for :page_title, page_title %>

<div class="title">
  <h1><%= link_to @album.title, album_photos_path(@album) %></h1>
  <% if has_album_rights? %>
    <div class="links">
      <%= link_to t('edit'), edit_album_photo_path(@album, @photo) %> |
      <%= link_to t('delete'), album_photo_path(@album, @photo), confirm: t('photos.edit.delete_msg'), method: :delete %> |
    </div>
  <% end %>
</div>
<%= render 'messages' %>

<div class="previewHolder">
  <div class="imgHolder">
    <%= image_tag(@photo.file.preview.url) %>
  </div>
  <div class="photoLinks">
    <%= @photo.previous_photo_tag %>
    <%= @photo.next_photo_tag %>
  </div>
  <div class="clear"></div>
  <div class="previewInfo">
      <% if @photo.title && !@photo.title.empty? %>
        <h2>"<%= @photo.title %>"</h2>
      <% end %>
      <p>
        <b><%= t('.author') %>:</b>
        <%= link_to image_tag(@user.avatar_src(:small), border: 0), user_albums_path(@user), title: t('albums.index.albums_of', user: @user.username) %>
      </p>
      <% if @photo.place_taken && !@photo.place_taken.empty? %>
        <p>
          <b><%= Photo.human_attribute_name('place_taken') %>:</b>
          <%= @photo.place_taken %>
        </p>
      <% end %>
      <% if @photo.camera_model && !@photo.camera_model.empty? %>
        <p>
          <b><%= Photo.human_attribute_name('camera_model') %>:</b>
          <%= @photo.camera_model %>
        </p>
      <% end %>
      <% if @photo.date_taken && !@photo.date_taken.blank? %>
        <p>
          <b><%= Photo.human_attribute_name('date_taken') %>:</b>
          <%= @photo.date_taken %>
        </p>
      <% end %>
      <% if @photo.exposure_time && !@photo.exposure_time.empty? %>
        <p>
          <b><%= Photo.human_attribute_name('exposure_time') %>:</b>
          <%= @photo.exposure_time %>
        </p>
      <% end %>
      <% if @photo.f_number && !@photo.f_number.empty? %>
        <p>
          <b><%= Photo.human_attribute_name('f_number') %>:</b>
          <%= @photo.f_number %>
        </p>
      <% end %>
      <% if @photo.iso_speed && !@photo.iso_speed.empty? %>
        <p>
          <b><%= Photo.human_attribute_name('iso_speed') %>:</b>
          <%= @photo.iso_speed %>
        </p>
      <% end %>
      <% if @photo.flash && !@photo.flash.empty? %>
        <p>
          <b><%= Photo.human_attribute_name('flash') %>:</b>
          <%= @photo.flash %>
        </p>
      <% end %>
      <% if @photo.flength_35mm_film && !@photo.flength_35mm_film.empty? %>
        <p>
          <b><%= Photo.human_attribute_name('flength_35mm_film') %>:</b>
          <%= @photo.flength_35mm_film %>
        </p>
      <% end %>
      <% if @photo.latitude && !@photo.latitude.nil? %>
        <p>
          <b><%= Photo.human_attribute_name('latitude') %>:</b>
          <%= @photo.latitude %>
        </p>
      <% end %>
      <% if @photo.longitude && !@photo.longitude.nil? %>
        <p>
          <b><%= Photo.human_attribute_name('longitude') %>:</b>
          <%= @photo.longitude %>
        </p>
      <% end %>
      <% if @photo.gps_address && !@photo.gps_address.empty? %>
        <p>
          <b><%= Photo.human_attribute_name('gps_address') %>:</b>
          <%= @photo.gps_address %>
        </p>
      <% end %>
      <p>
        <b><%= t('.viewed_x_times', count: @photo.views) %></b>
      </p>
    </div>
    <div class="clear"></div>
</div>

<%= render 'comments/index' %>

<% @comment = @photo.comments.build %>
<%= render 'comments/form' %>