config/routes.rb
Photodiary::Application.routes.draw do

  root to: 'home#index'
  
  resources :users do
    resources :albums
  end
  
  resources :albums do
    resources :photos do
      resources :comments
    end
  end
  
  match '/login', to: 'users#login', via: :get
  match '/login', to: 'users#login_process', via: :post
  match '/logout', to: 'users#logout'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :load_current_user

  helper_method :current_user, :has_album_rights?, :has_user_riths?, :logged_in?

  protect_from_forgery

  private

  def logged_in?
    session[:current_user] ? true : false
  end

  def load_current_user
    if logged_in?
      @current_user = User.find(session[:current_user])
    else
      nil
    end
  end

  def current_user
    @current_user ? @current_user : nil
  end

  def require_login
    unless logged_in?
      flash[:error] = t('mustbeloged_error')
      redirect_to root_path
    end
  end

  def is_owner?(owner_id)
    if current_user && current_user.id == owner_id
      true
    else
      flash[:error] = t('mustbeyours_error')
      false
    end
  end

  def has_album_rights?
    current_user && @album.user_id == current_user.id
  end

  def has_user_riths?
    current_user && @user.id == current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_messages.html.erb
<% if flash[:message] %>
  <div class="message_explanation">
    <h2><%= flash[:message] %></h2>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="error_explanation">
    <h2><%= flash[:error] %></h2>
  </div>
<% end %>

<% if defined?(@user) && @user.errors.any? %>
  <div class="error_explanation">
    <h2><%= t('error_occur', count: @user.errors.count) %>:</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if defined?(@album) && @album.errors.any? %>
  <div class="error_explanation">
    <h2><%= t('error_occur', count: @album.errors.count) %>:</h2>
    <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if defined?(@photo) && @photo.errors.any? %>
  <div class="error_explanation">
    <h2><%= t('error_occur', count: @photo.errors.count) %>:</h2>
    <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_navigation.html.erb
  <div class="topHolder">
    <div class="topNavigation">
      <ul class="nav">
        <li><%= link_to "", root_path, title: t('home'), class: "topLogo" %></li>
        <li><%= link_to t('users_list'), users_path %></li>
        <% if logged_in? %>
          <li><%= link_to t('users.show.profile'), session[:current_user] %></li>
          <li><%= link_to t('albums.index.my_albums'), user_albums_path(session[:current_user]) %></li>
          <li><%= link_to t('albums.new.new_album'), new_user_album_path(session[:current_user]) %></li>
          <li><%= link_to t('logout'), logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to t('users.new.registration'), new_user_path %></li>
          <li><%= link_to t('login'), login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>